services:
    nginx:
        image: nginx:alpine
        ports: 
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - frontend
            - api
            - llm-worker
            - db
            - rabbitmq
            - flower
        networks:
            - medical-chatbot


    db:
        image: postgres:15-alpine
        container_name: medical-chatbot-postgres
        # ports:
            # - "5433:5432"
        expose:
            - "5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ../.env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d medical_chat"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - medical-chatbot

    api:
        build:
            context: ../services/api
            dockerfile: Dockerfile
        container_name: medical-chatbot-api
        volumes:
            - ../services/api:/app
        # ports:
        #     - "8000:8000"
        expose:
            - "8000"
        env_file:
            - ../.env
        depends_on:
            db:
                condition: service_healthy
        command: >
            sh -c "
              alembic upgrade head &&
              uvicorn main:app --host 0.0.0.0 --port 8000 --root-path /backend --reload
            "
        networks:
            - medical-chatbot
        environment:
            - PYTHONUNBUFFERED=1


    rabbitmq:
        image: rabbitmq:4-management
        container_name: rabbitmq
        env_file:
            - ../.env
        volumes:
            - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
        # ports:
        #     - "5673:5672" # RabbitMQ AMQP port
        #     - "15673:15672" # RabbitMQ Management UI port
        expose:
            - "5672"
            - "15672"
        networks:
            - medical-chatbot
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5


    llm-worker:
        build:
            context: ../services/llm-worker
            dockerfile: Dockerfile
        container_name: medical-chatbot-llm-worker
        volumes:
            - ../services/llm-worker:/app
        env_file:
            - ../.env
        depends_on:
            api:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        command: python app.py
        networks:
            - medical-chatbot
        environment:
            - PYTHONUNBUFFERED=1


    flower:
        image: mher/flower
        build:
            context: ../services/llm-worker
        env_file:
            - ../.env
        # ports:
        #     - "5555:5555"
        expose:
            - "5555"
        depends_on:
            llm-worker:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        command: bash -c "
            celery -A celery flower --url_prefix=flower"
        networks:
            - medical-chatbot
    

    frontend:
        build:
            context: ../frontend
            dockerfile: Dockerfile
        container_name: medical-chatbot-frontend
        volumes:
            - ../frontend:/app
            - /app/node_modules
        # ports:
        #     - "5173:5173"
        expose:
            - "5173"
        env_file:
            - ../frontend/.env
        depends_on:
            - api
            - llm-worker
        networks:
            - medical-chatbot


volumes:
    postgres_data:

networks:
    medical-chatbot:
        driver: bridge
